package com.example.events;

import java.util.ArrayList;

import android.app.Activity;
import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.view.LayoutInflater;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Toast;

public class MainActivity extends Activity {

	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_main);

		
	}

	@Override
	public boolean onCreateOptionsMenu(Menu menu) {

		// Inflate the menu; this adds items to the action bar if it is present.
		getMenuInflater().inflate(R.menu.main, menu);
		return true;
	}

	@Override
	public boolean onOptionsItemSelected(MenuItem item) {
		// Handle action bar item clicks here. The action bar will
		// automatically handle clicks on the Home/Up button, so long
		// as you specify a parent activity in AndroidManifest.xml.
		int id = item.getItemId();
		if (id == R.id.action_settings) {
			return true;
		}
		return super.onOptionsItemSelected(item);
	}

	/**
	 * A placeholder fragment containing a simple view.
	 */
	public static class PlaceholderFragment extends Fragment {

		public PlaceholderFragment() {
		}

		@Override
		public View onCreateView(LayoutInflater inflater, ViewGroup container,
				Bundle savedInstanceState) {
			View rootView = inflater.inflate(R.layout.fragment_main, container,
					false);
			return rootView;
		}
	}
	
	public void addNewEvent (View view)
	{
		// snippet to scan new qr code.
		 Toast.makeText(this,"so you want to scan qr code ?", Toast.LENGTH_SHORT).show(); // just to check functionality.
		 
		 // string is to be generated by the qr code.
		 // now, taking a sample url.
		 String xml_url = getString(R.string.sample_url);
		 System.out.println(xml_url);
		 
		 // testing to add a new fest.
		  int testId = 1;
		  String testName = "cello" ;
		  
		  Fest f = new Fest();
		  f.setId(testId);
		  f.setName(testName);
		  
		  DatabaseManager db = new DatabaseManager(this);
		  db.addFest(f);
		  
		  ArrayList<Fest> list = new ArrayList<Fest>();
		  list = db.getAllFests();
		  
		  f = list.get(0);
		  System.out.println(f.getName());
		  
		 
		 
	}
	
	public void openFests(View view)
	{
		// calling new activity to show fests.
		
		 Toast.makeText(this, "i won't open fests for you.get lost.", Toast.LENGTH_SHORT).show(); // just to check functionality.
	}

}
